# This file was autogenerated by `bun2nix`, editing it is not recommended.
# Consume it with `callPackage` in your actual derivation -> https://nixos-and-flakes.thiscute.world/nixpkgs/callpackage
{
  lib,
  fetchurl,
  gnutar,
  coreutils,
  runCommand,
  symlinkJoin,
  bun,
}: let
  # Set of Bun packages to install
  packages = {
    "@isaacs/cliui" = fetchurl {
      name = "@isaacs/cliui@8.0.2";
      url = "https://registry.npmjs.org/@isaacs/cliui/-/cliui-8.0.2.tgz";
      hash = "sha256-Na48aPwJ2wmnPCI8nJbnQoGKhcs+muZXSHaxV3dA5MI=";
    };
    "@npmcli/fs" = fetchurl {
      name = "@npmcli/fs@3.1.1";
      url = "https://registry.npmjs.org/@npmcli/fs/-/fs-3.1.1.tgz";
      hash = "sha256-Y5lalYpuM1LRvSmu6rGOWWH8DsNFAtUqygHx4m2TQ84=";
    };
    "@pkgjs/parseargs" = fetchurl {
      name = "@pkgjs/parseargs@0.11.0";
      url = "https://registry.npmjs.org/@pkgjs/parseargs/-/parseargs-0.11.0.tgz";
      hash = "sha256-VrFZ7X9cK8DfhRZSL96klmy4cIoBf7+j4UjNn8M2dCU=";
    };
    "@types/bun" = fetchurl {
      name = "@types/bun@1.2.4";
      url = "https://registry.npmjs.org/@types/bun/-/bun-1.2.4.tgz";
      hash = "sha256-O01ctlMKEB5nmokJir6UwrPEPWaW9zhiqS0YkwPVX9Y=";
    };
    "@types/cacache" = fetchurl {
      name = "@types/cacache@17.0.2";
      url = "https://registry.npmjs.org/@types/cacache/-/cacache-17.0.2.tgz";
      hash = "sha256-2W1pbODfvyWV2PbQi12gbKrlohBskqtlngGB6J/LTOs=";
    };
    "@types/lru-cache" = fetchurl {
      name = "@types/lru-cache@5.1.1";
      url = "https://registry.npmjs.org/@types/lru-cache/-/lru-cache-5.1.1.tgz";
      hash = "sha256-FwbpHoUMBFMEKhoyvfc6wDFUcdVQyX/YA6qK8cpzgVI=";
    };
    "@types/node" = fetchurl {
      name = "@types/node@22.13.5";
      url = "https://registry.npmjs.org/@types/node/-/node-22.13.5.tgz";
      hash = "sha256-jtFd0kKkgHHRYLsT8YUk7PgWSyu0nVwrUHm+IMzNRKQ=";
    };
    "@types/ws" = fetchurl {
      name = "@types/ws@8.5.14";
      url = "https://registry.npmjs.org/@types/ws/-/ws-8.5.14.tgz";
      hash = "sha256-SsUn5egoHI/5PcxHQwwtNupaBcwgePqjR3uTG7Ew37w=";
    };
    "aggregate-error" = fetchurl {
      name = "aggregate-error@3.1.0";
      url = "https://registry.npmjs.org/aggregate-error/-/aggregate-error-3.1.0.tgz";
      hash = "sha256-AzYMuLWrpCXGnt5y5GW714RxBCCQSMlSALa0MsmLIFs=";
    };
    "ansi-regex" = fetchurl {
      name = "ansi-regex@6.1.0";
      url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.1.0.tgz";
      hash = "sha256-BG9v4XYCtoaqUi3hk9YEanXlV5MzZbpR4+PY4fppTzw=";
    };
    "ansi-styles" = fetchurl {
      name = "ansi-styles@6.2.1";
      url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.1.tgz";
      hash = "sha256-aPDnPT8um3lKOI3H9OmhmCcCc6C8pIzWjc+eCM88XRg=";
    };
    "balanced-match" = fetchurl {
      name = "balanced-match@1.0.2";
      url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
      hash = "sha256-2FT3q90MeoEgzzgeCtX5csvQJV9dmHQkvWcsjE/OvME=";
    };
    "brace-expansion" = fetchurl {
      name = "brace-expansion@2.0.1";
      url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
      hash = "sha256-JGQSfaQdpQ35coHEzb7rZrNTyO69CcNVB7tknmbYAUE=";
    };
    "bun-types" = fetchurl {
      name = "bun-types@1.2.4";
      url = "https://registry.npmjs.org/bun-types/-/bun-types-1.2.4.tgz";
      hash = "sha256-lXqzNu+EFE1bzON4rLGrSdws76vuyStC1Ehxa3n/6/0=";
    };
    "cacache" = fetchurl {
      name = "cacache@18.0.4";
      url = "https://registry.npmjs.org/cacache/-/cacache-18.0.4.tgz";
      hash = "sha256-gchzU2eq7kW2IXgV2Gdo+vOOmw2MwvhOKEeYCGA4/A4=";
    };
    "cacache/lru-cache" = fetchurl {
      name = "lru-cache@10.4.3";
      url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.4.3.tgz";
      hash = "sha256-DqF7UnvqqqxQTqenqquQ2wWB3JouEXv726RHifFUlu0=";
    };
    "chownr" = fetchurl {
      name = "chownr@2.0.0";
      url = "https://registry.npmjs.org/chownr/-/chownr-2.0.0.tgz";
      hash = "sha256-m+JdV/5AjU2zkmPA5lYkRyVfVjmoIs9FcKIFW13T/Jw=";
    };
    "clean-stack" = fetchurl {
      name = "clean-stack@2.2.0";
      url = "https://registry.npmjs.org/clean-stack/-/clean-stack-2.2.0.tgz";
      hash = "sha256-BWw3Zgq4xv9g5bJbiDJBwzVHj+6cGrHsTBW/iRz1VlU=";
    };
    "color-convert" = fetchurl {
      name = "color-convert@2.0.1";
      url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
      hash = "sha256-kg+kNTjAGaCF278Ey29yzDN2JOX1IXUZ8Oey73hOfOE=";
    };
    "color-name" = fetchurl {
      name = "color-name@1.1.4";
      url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
      hash = "sha256-UHt8RGHo65QTVa+aWemn4CzQ58YXa0jRgJdmNE8/Fwg=";
    };
    "cross-spawn" = fetchurl {
      name = "cross-spawn@7.0.6";
      url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
      hash = "sha256-GIwyDNxBOt/sAwmP2nKvepsCFSuhPTqPh/Fy2TztOOo=";
    };
    "eastasianwidth" = fetchurl {
      name = "eastasianwidth@0.2.0";
      url = "https://registry.npmjs.org/eastasianwidth/-/eastasianwidth-0.2.0.tgz";
      hash = "sha256-7M+hK72nH5+OCd560aTlVDaaa01D1/hghehQVahpTCc=";
    };
    "emoji-regex" = fetchurl {
      name = "emoji-regex@9.2.2";
      url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-9.2.2.tgz";
      hash = "sha256-HceN+oCyOr0Mo2UB6qMkHOFEDCR4sqnaIHGKJrxnrn4=";
    };
    "foreground-child" = fetchurl {
      name = "foreground-child@3.3.1";
      url = "https://registry.npmjs.org/foreground-child/-/foreground-child-3.3.1.tgz";
      hash = "sha256-r5zKW7BQBJytwBv0oBr1G/C8CaogmqbERYtFy1XBZz4=";
    };
    "fs-minipass" = fetchurl {
      name = "fs-minipass@3.0.3";
      url = "https://registry.npmjs.org/fs-minipass/-/fs-minipass-3.0.3.tgz";
      hash = "sha256-QT2Y3dWxTkrYJr4lQgjjs3as3LnK+3Kzl9wm3FlAalg=";
    };
    "glob" = fetchurl {
      name = "glob@10.4.5";
      url = "https://registry.npmjs.org/glob/-/glob-10.4.5.tgz";
      hash = "sha256-tKQWTGgX4f2wPzBvWzDLWtL0ZtcQdbHo4l69I7nmKAk=";
    };
    "imurmurhash" = fetchurl {
      name = "imurmurhash@0.1.4";
      url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
      hash = "sha256-rCOgMZZqc3HRkuNceFKrMcdyt9TkaN3Yhq08AUNyy2A=";
    };
    "indent-string" = fetchurl {
      name = "indent-string@4.0.0";
      url = "https://registry.npmjs.org/indent-string/-/indent-string-4.0.0.tgz";
      hash = "sha256-vGt009dOs0HItZDGl8f80lnG/RIjxLRNv7EYh86YQqA=";
    };
    "is-fullwidth-code-point" = fetchurl {
      name = "is-fullwidth-code-point@3.0.0";
      url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
      hash = "sha256-b0Fdrl3GBw8bQtruYWXquUGpcQGYIwX6zIuv2vMAvEo=";
    };
    "isexe" = fetchurl {
      name = "isexe@2.0.0";
      url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
      hash = "sha256-R8/ocuCI4oxTtzb+8wUyS1fMHPyfcqmw92n5JzHLg1k=";
    };
    "jackspeak" = fetchurl {
      name = "jackspeak@3.4.3";
      url = "https://registry.npmjs.org/jackspeak/-/jackspeak-3.4.3.tgz";
      hash = "sha256-3a3oIV/AQzhUZwuOs4+kIaFZcl4Wnt7tBVs0m6RELkw=";
    };
    "lru-cache" = fetchurl {
      name = "lru-cache@5.1.1";
      url = "https://registry.npmjs.org/lru-cache/-/lru-cache-5.1.1.tgz";
      hash = "sha256-sR54gZVEpmBuMxdkelWTwQLqONPFr65izWP5wsNpSFo=";
    };
    "minimatch" = fetchurl {
      name = "minimatch@9.0.5";
      url = "https://registry.npmjs.org/minimatch/-/minimatch-9.0.5.tgz";
      hash = "sha256-F9EHpLE+LdT0t96s8i+X35hPjXDamF/dgGQrFLEEX40=";
    };
    "minipass" = fetchurl {
      name = "minipass@7.1.2";
      url = "https://registry.npmjs.org/minipass/-/minipass-7.1.2.tgz";
      hash = "sha256-VI9WGhlDSXElTwnyFITGv50bnQN82sYjEGFrNRxE1RY=";
    };
    "minipass-collect" = fetchurl {
      name = "minipass-collect@2.0.1";
      url = "https://registry.npmjs.org/minipass-collect/-/minipass-collect-2.0.1.tgz";
      hash = "sha256-Gk0JTYkLn6VC4WCKc77ynpA4n6iWDkBEHF0lKE18QJc=";
    };
    "minipass-flush" = fetchurl {
      name = "minipass-flush@1.0.5";
      url = "https://registry.npmjs.org/minipass-flush/-/minipass-flush-1.0.5.tgz";
      hash = "sha256-Ut+ETPX7U5xnGi1FeMkieZ8m7zIRfh0DgMEqHqAFBOY=";
    };
    "minipass-flush/minipass" = fetchurl {
      name = "minipass@3.3.6";
      url = "https://registry.npmjs.org/minipass/-/minipass-3.3.6.tgz";
      hash = "sha256-etKQdEOiGUeALI5Py7fs1vG2bz0Kg5CCNdk6IXTPnl0=";
    };
    "minipass-flush/minipass/yallist" = fetchurl {
      name = "yallist@4.0.0";
      url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
      hash = "sha256-qAx4qidlNmFYke9m77wX070HyMsU471SmO7TAGv6TUk=";
    };
    "minipass-pipeline" = fetchurl {
      name = "minipass-pipeline@1.2.4";
      url = "https://registry.npmjs.org/minipass-pipeline/-/minipass-pipeline-1.2.4.tgz";
      hash = "sha256-C2TyODL9Y5G4eRgmFcbQNjNxsN8vo3p9Y+MJA7FWB48=";
    };
    "minipass-pipeline/minipass" = fetchurl {
      name = "minipass@3.3.6";
      url = "https://registry.npmjs.org/minipass/-/minipass-3.3.6.tgz";
      hash = "sha256-etKQdEOiGUeALI5Py7fs1vG2bz0Kg5CCNdk6IXTPnl0=";
    };
    "minipass-pipeline/minipass/yallist" = fetchurl {
      name = "yallist@4.0.0";
      url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
      hash = "sha256-qAx4qidlNmFYke9m77wX070HyMsU471SmO7TAGv6TUk=";
    };
    "minizlib" = fetchurl {
      name = "minizlib@2.1.2";
      url = "https://registry.npmjs.org/minizlib/-/minizlib-2.1.2.tgz";
      hash = "sha256-RO0Rii0Im7Rd6+pSR0hsTca/96HEooo0OXxoX+Kwzu0=";
    };
    "minizlib/minipass" = fetchurl {
      name = "minipass@3.3.6";
      url = "https://registry.npmjs.org/minipass/-/minipass-3.3.6.tgz";
      hash = "sha256-etKQdEOiGUeALI5Py7fs1vG2bz0Kg5CCNdk6IXTPnl0=";
    };
    "minizlib/yallist" = fetchurl {
      name = "yallist@4.0.0";
      url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
      hash = "sha256-qAx4qidlNmFYke9m77wX070HyMsU471SmO7TAGv6TUk=";
    };
    "mkdirp" = fetchurl {
      name = "mkdirp@1.0.4";
      url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
      hash = "sha256-HRcHTkGvb+jxyA34P0Ouql4cKDlFHyYTyuquTwJT2Bo=";
    };
    "p-map" = fetchurl {
      name = "p-map@4.0.0";
      url = "https://registry.npmjs.org/p-map/-/p-map-4.0.0.tgz";
      hash = "sha256-oTAjdWHD7rdaJaIVITrmQjvBtXEjs2BSj9lFcDUx/5A=";
    };
    "package-json-from-dist" = fetchurl {
      name = "package-json-from-dist@1.0.1";
      url = "https://registry.npmjs.org/package-json-from-dist/-/package-json-from-dist-1.0.1.tgz";
      hash = "sha256-E1xIPkNonQ4XscVt1eLf6mOk1K/HSdx+1rZrl/e8TiA=";
    };
    "path-key" = fetchurl {
      name = "path-key@3.1.1";
      url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
      hash = "sha256-S4mZrLkUgw7c08W4/sYysyxrx1msPtyGM29angi6e5I=";
    };
    "path-scurry" = fetchurl {
      name = "path-scurry@1.11.1";
      url = "https://registry.npmjs.org/path-scurry/-/path-scurry-1.11.1.tgz";
      hash = "sha256-/c44HNCLMHiW92/CqRXjmsu+hmnpwlJqM8BMI3kkNAk=";
    };
    "path-scurry/lru-cache" = fetchurl {
      name = "lru-cache@10.4.3";
      url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.4.3.tgz";
      hash = "sha256-DqF7UnvqqqxQTqenqquQ2wWB3JouEXv726RHifFUlu0=";
    };
    "semver" = fetchurl {
      name = "semver@7.7.1";
      url = "https://registry.npmjs.org/semver/-/semver-7.7.1.tgz";
      hash = "sha256-Dxu6Zt/NN/UsYqM6USTi8vccltvIAge4MP/LyM1bXeU=";
    };
    "shebang-command" = fetchurl {
      name = "shebang-command@2.0.0";
      url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
      hash = "sha256-msulvRilHpzfWJg4Dk32P4A+GETe9krhpG+Iz/htVW4=";
    };
    "shebang-regex" = fetchurl {
      name = "shebang-regex@3.0.0";
      url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
      hash = "sha256-/turqm2ybGvgGD+Cd336hS1Zpi+Ihd6TvTLrwodYlY8=";
    };
    "signal-exit" = fetchurl {
      name = "signal-exit@4.1.0";
      url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
      hash = "sha256-nTtYqBHs9qZBU3OHKJJ0zRT1u5EqJ+Tx8qdBgryot5U=";
    };
    "ssri" = fetchurl {
      name = "ssri@10.0.6";
      url = "https://registry.npmjs.org/ssri/-/ssri-10.0.6.tgz";
      hash = "sha256-3WpBm07p1SVYC9F9mjsbXp3ULGdih/uj8xj9LEGKlBQ=";
    };
    "string-width" = fetchurl {
      name = "string-width@5.1.2";
      url = "https://registry.npmjs.org/string-width/-/string-width-5.1.2.tgz";
      hash = "sha256-QQkRob3LiqCCXc6S90v3SfwI3aqVub59y+eVQ2AU9Dc=";
    };
    "string-width-cjs" = fetchurl {
      name = "string-width@4.2.3";
      url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
      hash = "sha256-rbtPsbJugGmvma3/AHk2nJPxfPiHuRCGaR1nHdvVKTQ=";
    };
    "string-width-cjs/emoji-regex" = fetchurl {
      name = "emoji-regex@8.0.0";
      url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
      hash = "sha256-tczZ+/sICY7vvra2tLQNtts6z5JD4yfgOZJaqGYcsQc=";
    };
    "string-width-cjs/strip-ansi" = fetchurl {
      name = "strip-ansi@6.0.1";
      url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
      hash = "sha256-m9t10L/0nxVt2MO8sOBrP6lsPYjd1MNCpDRYZqQMCMo=";
    };
    "string-width-cjs/strip-ansi/ansi-regex" = fetchurl {
      name = "ansi-regex@5.0.1";
      url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
      hash = "sha256-Dg6tzaragF212FtTrVzcoHYLmW7hmeyWWOezSqbI4Nk=";
    };
    "strip-ansi" = fetchurl {
      name = "strip-ansi@7.1.0";
      url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.0.tgz";
      hash = "sha256-lMSjCUaQVYsbBvVFG8OAGW0taEsolTdjNUIcFXqzk3E=";
    };
    "strip-ansi-cjs" = fetchurl {
      name = "strip-ansi@6.0.1";
      url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
      hash = "sha256-m9t10L/0nxVt2MO8sOBrP6lsPYjd1MNCpDRYZqQMCMo=";
    };
    "strip-ansi-cjs/ansi-regex" = fetchurl {
      name = "ansi-regex@5.0.1";
      url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
      hash = "sha256-Dg6tzaragF212FtTrVzcoHYLmW7hmeyWWOezSqbI4Nk=";
    };
    "tar" = fetchurl {
      name = "tar@6.2.1";
      url = "https://registry.npmjs.org/tar/-/tar-6.2.1.tgz";
      hash = "sha256-1tAXoRJZaZbXOnH40yES7ZQodzGUFMDtyZ3b2BbtBuc=";
    };
    "tar/fs-minipass" = fetchurl {
      name = "fs-minipass@2.1.0";
      url = "https://registry.npmjs.org/fs-minipass/-/fs-minipass-2.1.0.tgz";
      hash = "sha256-/ZUrQMcNbOuHKfalEOJp9p69+Pem59PdA/chaJZsMwk=";
    };
    "tar/fs-minipass/minipass" = fetchurl {
      name = "minipass@3.3.6";
      url = "https://registry.npmjs.org/minipass/-/minipass-3.3.6.tgz";
      hash = "sha256-etKQdEOiGUeALI5Py7fs1vG2bz0Kg5CCNdk6IXTPnl0=";
    };
    "tar/minipass" = fetchurl {
      name = "minipass@5.0.0";
      url = "https://registry.npmjs.org/minipass/-/minipass-5.0.0.tgz";
      hash = "sha256-vnFYGGyPHxBeAN8xZ/2SohaY+CfhqKtwDUB+yXUG1z8=";
    };
    "tar/yallist" = fetchurl {
      name = "yallist@4.0.0";
      url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
      hash = "sha256-qAx4qidlNmFYke9m77wX070HyMsU471SmO7TAGv6TUk=";
    };
    "typescript" = fetchurl {
      name = "typescript@5.7.3";
      url = "https://registry.npmjs.org/typescript/-/typescript-5.7.3.tgz";
      hash = "sha256-gM/KElS6uOgdY5F45C1kBthW+6bjTK1g0atQ7m5ffrs=";
    };
    "undici-types" = fetchurl {
      name = "undici-types@6.20.0";
      url = "https://registry.npmjs.org/undici-types/-/undici-types-6.20.0.tgz";
      hash = "sha256-coyp/P9nY3Lk3NZIteJvu9sonsK89nXnYBzCE0pejW4=";
    };
    "unique-filename" = fetchurl {
      name = "unique-filename@3.0.0";
      url = "https://registry.npmjs.org/unique-filename/-/unique-filename-3.0.0.tgz";
      hash = "sha256-Zqy6G30UxEMVN36R0c6BtlOWEKoXXDd+nLKlr+vX46s=";
    };
    "unique-slug" = fetchurl {
      name = "unique-slug@4.0.0";
      url = "https://registry.npmjs.org/unique-slug/-/unique-slug-4.0.0.tgz";
      hash = "sha256-7FQvIp1qUlSC+o9Xz3PHRiUufcKTkq7abffgOgbvLpc=";
    };
    "which" = fetchurl {
      name = "which@2.0.2";
      url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
      hash = "sha256-oTrfX93rdpZV7c5VHoH7sRkEucm+dtleQdqMTEmdTtw=";
    };
    "wrap-ansi" = fetchurl {
      name = "wrap-ansi@8.1.0";
      url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-8.1.0.tgz";
      hash = "sha256-9xsrl7rCjexdcc4LfSBcKADr1Lf39Q6u5ct5Ih60rG0=";
    };
    "wrap-ansi-cjs" = fetchurl {
      name = "wrap-ansi@7.0.0";
      url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
      hash = "sha256-B5WzUQvS6Tj2pBU5bePU9Y/XbvH4JJoHGWRE6vhcpC8=";
    };
    "wrap-ansi-cjs/ansi-styles" = fetchurl {
      name = "ansi-styles@4.3.0";
      url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
      hash = "sha256-LFOaRthatgMxg5l0NNLZpcos7vwStNuQIvVkeEzXmH8=";
    };
    "wrap-ansi-cjs/string-width" = fetchurl {
      name = "string-width@4.2.3";
      url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
      hash = "sha256-rbtPsbJugGmvma3/AHk2nJPxfPiHuRCGaR1nHdvVKTQ=";
    };
    "wrap-ansi-cjs/string-width/emoji-regex" = fetchurl {
      name = "emoji-regex@8.0.0";
      url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
      hash = "sha256-tczZ+/sICY7vvra2tLQNtts6z5JD4yfgOZJaqGYcsQc=";
    };
    "wrap-ansi-cjs/strip-ansi" = fetchurl {
      name = "strip-ansi@6.0.1";
      url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
      hash = "sha256-m9t10L/0nxVt2MO8sOBrP6lsPYjd1MNCpDRYZqQMCMo=";
    };
    "wrap-ansi-cjs/strip-ansi/ansi-regex" = fetchurl {
      name = "ansi-regex@5.0.1";
      url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
      hash = "sha256-Dg6tzaragF212FtTrVzcoHYLmW7hmeyWWOezSqbI4Nk=";
    };
    "yallist" = fetchurl {
      name = "yallist@3.1.1";
      url = "https://registry.npmjs.org/yallist/-/yallist-3.1.1.tgz";
      hash = "sha256-UPFK5s/oNgyyJZuj6TMF4GkDbxMlHWnTy+6eHUd1ygQ=";
    };
  };

  # List of binary symlinks to create in the `node_modules/.bin` folder
  binaries = {
    "glob" = "../glob/dist/esm/bin.mjs";
    "mkdirp" = "../mkdirp/bin/cmd.js";
    "node-which" = "../which/./bin/node-which";
    "semver" = "../semver/bin/semver.js";
    "tsc" = "../typescript/bin/tsc";
    "tsserver" = "../typescript/bin/tsserver";
  };

  # Normalize a package path
  normalizePath = name:
    if lib.hasPrefix "@" name
    then name
    else if !lib.hasInfix "/" name
    then name
    else let
      parts = lib.strings.splitString "/" name;
      joiner = builtins.concatStringsSep "/node_modules/";
    in
      joiner parts;

  # Extract a package from a tar file
  extractPackage = name: pkg: let
    targetPath = normalizePath name;
  in
    runCommand "bun2nix-extract-${name}" {buildInputs = [gnutar coreutils];} ''
      echo ${targetPath}

      # Extract the npm download into the correctly resolved path based on the package name
      mkdir -p $out/${targetPath}
      tar -xzf ${pkg} -C $out/${targetPath} --strip-components=1

      # Patch any binaries in the package
      mkdir -p $out/bin
      ln -s ${bun}/bin/bun $out/bin/node
      PATH=$out/bin:$PATH patchShebangs $out/${targetPath}
      patchShebangs $out/${targetPath}
    '';

  # Link a binary from a package
  linkBin = name: dest:
    runCommand "bun2nix-binary-${name}" {} ''
      mkdir -p $out

      ln -sn ${dest} $out/${name}
    '';

  # Construct the .bin directory
  dotBinDir = symlinkJoin {
    name = ".bin";
    paths = lib.mapAttrsToList linkBin binaries;
  };

  # Link the packages to inject into node_modules
  packageFiles = symlinkJoin {
    name = "package-files";
    paths = lib.mapAttrsToList extractPackage packages;
  };

  # Build the node modules directory
  nodeModules = runCommand "node-modules" {} ''
    mkdir -p $out

    # Packages need to be regular folders
    cp -rL ${packageFiles}/* $out/

    # Executables need to be symlinks
    cp -r ${dotBinDir} $out/.bin
  '';
in {
  inherit nodeModules packages dotBinDir binaries;
}
