# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
# Consume this with `pkgs.callPackage` providing
# the `root` arg
{ fetchurl, ... }:
{
  "@types+bun@1.2.4" = fetchurl {
     url = "https://registry.npmjs.org/@types/bun/-/bun-1.2.4.tgz";
     hash = "sha512-QtuV5OMR8/rdKJs213iwXDpfVvnskPXY/S0ZiFbsTjQZycuqPbMW8Gf/XhLfwE5njW8sxI2WjISURXPlHypMFA==";
  };
  "@types+node@22.13.5" = fetchurl {
     url = "https://registry.npmjs.org/@types/node/-/node-22.13.5.tgz";
     hash = "sha512-+lTU0PxZXn0Dr1NBtC7Y8cR21AJr87dLLU953CWA6pMxxv/UDc7jYAY90upcrie1nRcD6XNG5HOYEDtgW5TxAg==";
  };
  "@types+ws@8.5.14" = fetchurl {
     url = "https://registry.npmjs.org/@types/ws/-/ws-8.5.14.tgz";
     hash = "sha512-bd/YFLW+URhBzMXurx7lWByOu+xzU9+kb3RboOteXYDfW+tr+JZa99OyNmPINEGB/ahzKrEuc8rcv4gnpJmxTw==";
  };
  "bun-types@1.2.4" = fetchurl {
     url = "https://registry.npmjs.org/bun-types/-/bun-types-1.2.4.tgz";
     hash = "sha512-nDPymR207ZZEoWD4AavvEaa/KZe/qlrbMSchqpQwovPZCKc7pwMoENjEtHgMKaAjJhy+x6vfqSBA1QU3bJgs0Q==";
  };
  "typescript@5.7.3" = fetchurl {
     url = "https://registry.npmjs.org/typescript/-/typescript-5.7.3.tgz";
     hash = "sha512-84MVSjMEHP+FQRPy3pX9sTVV/INIex71s9TL2Gm5FG/WG1SqXeKyZ0k7/blY/4FdOzI12CBy1vGc4og/eus0fw==";
  };
  "undici-types@6.20.0" = fetchurl {
     url = "https://registry.npmjs.org/undici-types/-/undici-types-6.20.0.tgz";
     hash = "sha512-Ny6QZ2Nju20vw1SRHe3d9jVu6gJ+4e3+MMpqu7pqE5HT6WsTSlce++GQmK5UXS8mzV8DSYHrQH+Xrf2jVcuKNg==";
  };
}