use itertools::Itertools;

use super::{Binaries, Fetched, Package};

/// # Nix Expression Conversion Trait
///
/// Implemented by anything that can be turned into a nix expression
pub trait DumpNixExpression {
    /// # Dump Nix Experession
    ///
    /// Dumps `self` into a nix expression
    fn dump_nix_expression(&self) -> String;
    ///
    /// # Dump Nix Binaries Experession
    ///
    /// Dumps `self` into a nix expression representing the binaries which need to beinstalled
    /// to `node_modules/.bin`
    fn dump_binaries_expression(&self) -> String;
}

impl DumpNixExpression for Package<Fetched> {
    fn dump_nix_expression(&self) -> String {
        format!(
"    \"{}\" = fetchurl {{
      name = \"{}\";
      url = \"{}\";
      hash = \"{}\";
    }};",
            self.name, self.npm_identifier, self.data.url, self.data.hash
        )
    }

    fn dump_binaries_expression(&self) -> String {
        match &self.data.binaries {
            Binaries::None => String::default(),
            Binaries::Unnamed(pathless_link) => {
                let link = format!("../{}/{}", self.name, pathless_link);

                format!("    {} = \"{}\";", self.name, link)
            }
            Binaries::Named(bin_map) =>
                bin_map
                    .iter()
                    .map(|(bin_name, pathless_link)| {
                        let link = format!("../{}/{}", self.name, pathless_link);

                        format!("    {} = \"{}\";", bin_name, link)
                    })
                    .sorted()
                    .reduce(|acc, n| acc + "\n" + &n)
                    .unwrap_or_default()
        }
    }
}

impl DumpNixExpression for Vec<Package<Fetched>> {
    fn dump_nix_expression(&self) -> String {
        let packages_section = self
            .iter()
            .map(|p| p.dump_nix_expression())
            .sorted()
            .reduce(|acc, e| acc + "\n" + &e)
            .unwrap_or_default();

        format!(
"# This file was autogenerated by `bun2nix`, editing it is not recommended.
# Consume it with `callPackage` in your actual derivation -> https://nixos-and-flakes.thiscute.world/nixpkgs/callpackage
{{
  lib,
  fetchurl,
  gnutar,
  coreutils,
  runCommand,
  symlinkJoin,
  bun,
}}: let
  # Bun packages to install
  packages = {{
{}
  }};

  # Extract a package from a tar file
  extractPackage = name: pkg:
    runCommand \"bun2nix-extract-${{name}}\" {{buildInputs = [gnutar coreutils];}} ''
      # Extract the files from npm
      mkdir -p $out/${{name}}
      tar -xzf ${{pkg.path}} -C $out/${{name}} --strip-components=1

      # Patch binary shebangs to point to bun
      mkdir -p $out/bin
      ln -s ${{bun}}/bin/bun $out/bin/node
      PATH=$out/bin:$PATH patchShebangs $out/${{name}}
      patchShebangs $out/${{name}}
    '';

  # List of binary symlinks to create in the `node_modules/.bin` folder
  binaries = {{
{}
  }};

  # Link a binary from a package
  linkBin = name: dest:
    runCommand \"bun2nix-binary-${{name}}\" {{}} ''
      mkdir -p $out

      ln -sn ${{dest}} $out/${{name}}
    '';

  # Construct the .bin directory
  dotBinDir = symlinkJoin {{
    name = \".bin\";
    paths = lib.mapAttrsToList linkBin binaries;
  }};

  # Link the packages to inject into node_modules
  packageFiles = symlinkJoin {{
    name = \"package-files\";
    paths = lib.mapAttrsToList extractPackage packages;
  }};

  # Build the node modules directory
  nodeModules = runCommand \"node-modules\" {{}} ''
    mkdir -p $out

    # Packages need to be regular folders
    cp -rL ${{packageFiles}}/* $out/

    # Executables need to be symlinks
    cp -r ${{dotBinDir}} $out/.bin
  '';
in {{
  inherit nodeModules packages dotBinDir binaries;
}}",
    packages_section, self.dump_binaries_expression())
    }

    fn dump_binaries_expression(&self) -> String {
        self
            .iter()
            .flat_map(|p| p.generate_binary_symlinks())
            .unique_by(|(name, _)| name.to_owned())
            .sorted()
            .map(|(name, symlink)| format!("    {} = \"{}\";", name, symlink))
            .collect::<Vec<_>>()
            .into_iter().join("\n")
    }
}

#[test]
fn test_dump_nix_expression_file() {
    use std::collections::HashMap;

    let out = vec![
        Package {
            name: "@alloc/quick-lru".to_owned(),
            npm_identifier: "@alloc/quick-lru@5.2.0".to_owned(),
            data: Fetched {
                binaries: Binaries::Named(HashMap::from([
                    ("binary_1".to_owned(), "first.js".to_owned()),
                    ("binary_2".to_owned(), "second.js".to_owned()),
                ])),
                hash: "sha256-w/Huz4+crTzdiSyQVAx0h3lhtTTrtPyKp3xpQD5EG9g=".to_owned(),
                url: "https://registry.npmjs.org/@alloc/quick-lru/-/quick-lru-5.2.0.tgz".to_owned(),
            }
        },
        Package {
            name: "other-package".to_owned(),
            npm_identifier: "other-package@4.2.0".to_owned(),
            data: Fetched {
                binaries: Binaries::Unnamed("cli.js".to_owned()),
                hash: "sha256-w/Huz4+crTzdiSyQVAx0h3lhtTTrtPyKp3xpQD5EG9g=".to_owned(),
                url: "https://registry.npmjs.org/other-package/-/other-package-4.2.0.tgz".to_owned(),
            }
        }
    ];

    let expected = 
"# This file was autogenerated by `bun2nix`, editing it is not recommended.
# Consume it with `callPackage` in your actual derivation -> https://nixos-and-flakes.thiscute.world/nixpkgs/callpackage
{
  lib,
  fetchurl,
  gnutar,
  coreutils,
  runCommand,
  symlinkJoin,
  bun,
}: let
  # Bun packages to install
  packages = {
    \"@alloc/quick-lru\" = fetchurl {
      name = \"@alloc/quick-lru@5.2.0\";
      url  = \"https://registry.npmjs.org/@alloc/quick-lru/-/quick-lru-5.2.0.tgz\";
      hash = \"sha256-w/Huz4+crTzdiSyQVAx0h3lhtTTrtPyKp3xpQD5EG9g=\";
    };
    \"other-package\" = fetchurl {
      name = \"other-package@4.2.0\";
      url  = \"https://registry.npmjs.org/other-package/-/other-package-4.2.0.tgz\";
      hash = \"sha256-w/Huz4+crTzdiSyQVAx0h3lhtTTrtPyKp3xpQD5EG9g=\";
    };
  };

  # Extract a package from a tar file
  extractPackage = name: pkg:
    runCommand \"bun2nix-extract-${name}\" {buildInputs = [gnutar coreutils];} ''
      # Extract the files from npm
      mkdir -p $out/${name}
      tar -xzf ${pkg.path} -C $out/${name} --strip-components=1

      # Patch binary shebangs to point to bun
      mkdir -p $out/bin
      ln -s ${bun}/bin/bun $out/bin/node
      PATH=$out/bin:$PATH patchShebangs $out/${name}
      patchShebangs $out/${name}
    '';

  # List of binary symlinks to create in the `node_modules/.bin` folder
  binaries = {
    binary_1 = \"../@alloc/quick-lru/first.js\";
    binary_2 = \"../@alloc/quick-lru/second.js\";
    other-package = \"../other-package/cli.js\";
  };

  # Link a binary from a package
  linkBin = name: dest:
    runCommand \"bun2nix-binary-${name}\" {} ''
      mkdir -p $out

      ln -sn ${dest} $out/${name}
    '';

  # Construct the .bin directory
  dotBinDir = symlinkJoin {
    name = \".bin\";
    paths = lib.mapAttrsToList linkBin binaries;
  };

  # Link the packages to inject into node_modules
  packageFiles = symlinkJoin {
    name = \"package-files\";
    paths = lib.mapAttrsToList extractPackage packages;
  };

  # Build the node modules directory
  nodeModules = runCommand \"node-modules\" {} ''
    mkdir -p $out

    # Packages need to be regular folders
    cp -rL ${packageFiles}/* $out/

    # Executables need to be symlinks
    cp -r ${dotBinDir} $out/.bin
  '';
in {
  inherit nodeModules packages dotBinDir binaries;
}";

    assert_eq!(expected.trim(), out.dump_nix_expression().trim());
}

