# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
# Consume this with `pkgs.callPackage` providing
# the `root` arg
{
  fetchurl,
  root,
  copyPathToStore,
  ...
}:
{
  "@workspace/app" = copyPathToStore "${root}/packages/app";
  "@workspace/lib" = copyPathToStore "${root}/packages/lib";
  "is-number@6.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-number/-/is-number-6.0.0.tgz";
    hash = "sha512-Wu1VHeILBK8KAWJUAiSZQX94GmOE45Rg6/538fKwiloUu21KncEkYGPqob2oSZ5mUT73vLGrHQjKw3KMPwfDzg==";
  };
  "is-odd@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/is-odd/-/is-odd-3.0.1.tgz";
    hash = "sha512-CQpnWPrDwmP1+SMHXZhtLtJv90yiyVfluGsX5iNCVkrhQtU3TQHsUWPG9wkdk9Lgd5yNpAg9jQEo90CBaXgWMA==";
  };
}
