# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{ fetchurl, copyPathToStore, ... }:
{
  "@workspace/app" = copyPathToStore "./packages/app";
  "@workspace/lib" = copyPathToStore "./packages/lib";
  "is-number@6.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-number/-/is-number-6.0.0.tgz";
    hash = "sha512-Wu1VHeILBK8KAWJUAiSZQX94GmOE45Rg6/538fKwiloUu21KncEkYGPqob2oSZ5mUT73vLGrHQjKw3KMPwfDzg==";
  };
  "is-odd@3.0.1" = fetchurl {
    url = "https://registry.npmjs.org/is-odd/-/is-odd-3.0.1.tgz";
    hash = "sha512-CQpnWPrDwmP1+SMHXZhtLtJv90yiyVfluGsX5iNCVkrhQtU3TQHsUWPG9wkdk9Lgd5yNpAg9jQEo90CBaXgWMA==";
  };
}
