# This file was autogenerated by `bun2nix`, editing it is not recommended.
# Consume it with `callPackage` in your actual derivation -> https://nixos-and-flakes.thiscute.world/nixpkgs/callpackage
{
  lib,
  fetchurl,
  runCommand,
  gnutar,
  bun,
  makeWrapper,
  ...
}: let
  # Set of Bun packages to install
  packages = {
    "@types/bun" = {
      out_path = "@types/bun";
      binaries = {
      };
      pkg = fetchurl {
        name = "@types/bun@1.2.4";
        url = "https://registry.npmjs.org/@types/bun/-/bun-1.2.4.tgz";
        hash = "sha256-O01ctlMKEB5nmokJir6UwrPEPWaW9zhiqS0YkwPVX9Y=";
      };
    };
    "@types/node" = {
      out_path = "@types/node";
      binaries = {
      };
      pkg = fetchurl {
        name = "@types/node@22.13.5";
        url = "https://registry.npmjs.org/@types/node/-/node-22.13.5.tgz";
        hash = "sha256-jtFd0kKkgHHRYLsT8YUk7PgWSyu0nVwrUHm+IMzNRKQ=";
      };
    };
    "@types/react" = {
      out_path = "@types/react";
      binaries = {
      };
      pkg = fetchurl {
        name = "@types/react@19.0.10";
        url = "https://registry.npmjs.org/@types/react/-/react-19.0.10.tgz";
        hash = "sha256-cKe1P9eluhnbnhaOIVOqoRF6iUwJCQJX3ZWDL46Uank=";
      };
    };
    "@types/react-dom" = {
      out_path = "@types/react-dom";
      binaries = {
      };
      pkg = fetchurl {
        name = "@types/react-dom@19.0.4";
        url = "https://registry.npmjs.org/@types/react-dom/-/react-dom-19.0.4.tgz";
        hash = "sha256-rJnqfJ6tOL2GEZ43gL3ib8C8wKNEqBZkKU3zm3kONDw=";
      };
    };
    "@types/ws" = {
      out_path = "@types/ws";
      binaries = {
      };
      pkg = fetchurl {
        name = "@types/ws@8.5.14";
        url = "https://registry.npmjs.org/@types/ws/-/ws-8.5.14.tgz";
        hash = "sha256-SsUn5egoHI/5PcxHQwwtNupaBcwgePqjR3uTG7Ew37w=";
      };
    };
    "bun-plugin-tailwind" = {
      out_path = "bun-plugin-tailwind";
      binaries = {
      };
      pkg = fetchurl {
        name = "bun-plugin-tailwind@0.0.14";
        url = "https://registry.npmjs.org/bun-plugin-tailwind/-/bun-plugin-tailwind-0.0.14.tgz";
        hash = "sha256-nQViPxk9Oiz+kZWKoeA1k2MD/t+DMbIQLlOZUQk1TgA=";
      };
    };
    "bun-plugin-tailwind/tailwindcss" = {
      out_path = "bun-plugin-tailwind/node_modules/tailwindcss";
      binaries = {
      };
      pkg = fetchurl {
        name = "tailwindcss@4.0.0-beta.9";
        url = "https://registry.npmjs.org/tailwindcss/-/tailwindcss-4.0.0-beta.9.tgz";
        hash = "sha256-9GTG+7bBUxKu0n/g42Ri4NRiGaREm+dq/mzLOcOX73g=";
      };
    };
    "bun-types" = {
      out_path = "bun-types";
      binaries = {
      };
      pkg = fetchurl {
        name = "bun-types@1.2.4";
        url = "https://registry.npmjs.org/bun-types/-/bun-types-1.2.4.tgz";
        hash = "sha256-lXqzNu+EFE1bzON4rLGrSdws76vuyStC1Ehxa3n/6/0=";
      };
    };
    "csstype" = {
      out_path = "csstype";
      binaries = {
      };
      pkg = fetchurl {
        name = "csstype@3.1.3";
        url = "https://registry.npmjs.org/csstype/-/csstype-3.1.3.tgz";
        hash = "sha256-Lwg/fPKjmPBaYktO+isUSWxF53zSsSoGR+JpdWcYZ3c=";
      };
    };
    "react" = {
      out_path = "react";
      binaries = {
      };
      pkg = fetchurl {
        name = "react@19.0.0";
        url = "https://registry.npmjs.org/react/-/react-19.0.0.tgz";
        hash = "sha256-IXjsAtQcCfYLWn3CGER4ev0KQfJo+qbqmsegbM9k7KY=";
      };
    };
    "react-dom" = {
      out_path = "react-dom";
      binaries = {
      };
      pkg = fetchurl {
        name = "react-dom@19.0.0";
        url = "https://registry.npmjs.org/react-dom/-/react-dom-19.0.0.tgz";
        hash = "sha256-Ug6qBE6TJehvkLmHEQOd/UojK7p90g69MrCVp7Y3eXc=";
      };
    };
    "scheduler" = {
      out_path = "scheduler";
      binaries = {
      };
      pkg = fetchurl {
        name = "scheduler@0.25.0";
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.25.0.tgz";
        hash = "sha256-iqwtpt7LCcHaz4wQb2LS+0RU+7H98vb+bU7xpXt8aRQ=";
      };
    };
    "tailwindcss" = {
      out_path = "tailwindcss";
      binaries = {
      };
      pkg = fetchurl {
        name = "tailwindcss@4.0.9";
        url = "https://registry.npmjs.org/tailwindcss/-/tailwindcss-4.0.9.tgz";
        hash = "sha256-kw0dfQQ5MRjcvU8Vrs5nTIsOWIsqqNx9tPFvk+xxSvQ=";
      };
    };
    "typescript" = {
      out_path = "typescript";
      binaries = {
        "tsc" = "../typescript/bin/tsc";
        "tsserver" = "../typescript/bin/tsserver";
      };
      pkg = fetchurl {
        name = "typescript@5.7.3";
        url = "https://registry.npmjs.org/typescript/-/typescript-5.7.3.tgz";
        hash = "sha256-gM/KElS6uOgdY5F45C1kBthW+6bjTK1g0atQ7m5ffrs=";
      };
    };
    "undici-types" = {
      out_path = "undici-types";
      binaries = {
      };
      pkg = fetchurl {
        name = "undici-types@6.20.0";
        url = "https://registry.npmjs.org/undici-types/-/undici-types-6.20.0.tgz";
        hash = "sha256-coyp/P9nY3Lk3NZIteJvu9sonsK89nXnYBzCE0pejW4=";
      };
    };
  };

  # Build the node modules directory
  nodeModules = runCommand "node-modules" {
    nativeBuildInputs = [ 
      gnutar 
      makeWrapper
    ];
  } ''
    mkdir -p $out/node_modules/.bin

    # Extract a given package to it's destination
    extract() {
      local pkg=$1
      local dest=$2
      
      mkdir -p "$dest"
      tar -xzf "$pkg" -C "$dest" --strip-components=1
    }

    # Process each package
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: pkg: ''
      echo "Installing package ${name}..."

      mkdir -p "$out/node_modules/${pkg.out_path}"
      extract "${pkg.pkg}" "$out/node_modules/${pkg.out_path}"
      
      # Handle binaries if they exist
      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (binName: binPath: ''
        ln -sf "${binPath}" "$out/node_modules/.bin/${binName}"
      '') pkg.binaries)}
    '') packages)}

    # Force bun instead of node for script execution
    makeWrapper ${bun}/bin/bun $out/bin/node
    export PATH="$out/bin:$PATH"

    patchShebangs $out/node_modules
  '';

in {
  inherit nodeModules packages;
}
