# This file was autogenerated by `bun2nix`, editing it is not recommended.
# Consume it with `callPackage` in your actual derivation -> https://nixos-and-flakes.thiscute.world/nixpkgs/callpackage
{
  fetchurl,
  gnutar,
  coreutils,
  runCommand,
  symlinkJoin,
}: let
  # Bun packages to install
  packages = [
    {
      name = "tailwindcss";
      path = fetchurl {
        name = "tailwindcss@4.0.0-beta.9";
        url  = "https://registry.npmjs.org/tailwindcss/-/tailwindcss-4.0.0-beta.9.tgz";
        hash = "sha256-9GTG+7bBUxKu0n/g42Ri4NRiGaREm+dq/mzLOcOX73g=";
      };
    }
    {
      name = "react";
      path = fetchurl {
        name = "react@19.0.0";
        url  = "https://registry.npmjs.org/react/-/react-19.0.0.tgz";
        hash = "sha256-IXjsAtQcCfYLWn3CGER4ev0KQfJo+qbqmsegbM9k7KY=";
      };
    }
    {
      name = "csstype";
      path = fetchurl {
        name = "csstype@3.1.3";
        url  = "https://registry.npmjs.org/csstype/-/csstype-3.1.3.tgz";
        hash = "sha256-Lwg/fPKjmPBaYktO+isUSWxF53zSsSoGR+JpdWcYZ3c=";
      };
    }
    {
      name = "@types/bun";
      path = fetchurl {
        name = "@types/bun@1.2.4";
        url  = "https://registry.npmjs.org/@types/bun/-/bun-1.2.4.tgz";
        hash = "sha256-O01ctlMKEB5nmokJir6UwrPEPWaW9zhiqS0YkwPVX9Y=";
      };
    }
    {
      name = "@types/ws";
      path = fetchurl {
        name = "@types/ws@8.5.14";
        url  = "https://registry.npmjs.org/@types/ws/-/ws-8.5.14.tgz";
        hash = "sha256-SsUn5egoHI/5PcxHQwwtNupaBcwgePqjR3uTG7Ew37w=";
      };
    }
    {
      name = "react-dom";
      path = fetchurl {
        name = "react-dom@19.0.0";
        url  = "https://registry.npmjs.org/react-dom/-/react-dom-19.0.0.tgz";
        hash = "sha256-Ug6qBE6TJehvkLmHEQOd/UojK7p90g69MrCVp7Y3eXc=";
      };
    }
    {
      name = "@types/react";
      path = fetchurl {
        name = "@types/react@19.0.10";
        url  = "https://registry.npmjs.org/@types/react/-/react-19.0.10.tgz";
        hash = "sha256-cKe1P9eluhnbnhaOIVOqoRF6iUwJCQJX3ZWDL46Uank=";
      };
    }
    {
      name = "undici-types";
      path = fetchurl {
        name = "undici-types@6.20.0";
        url  = "https://registry.npmjs.org/undici-types/-/undici-types-6.20.0.tgz";
        hash = "sha256-coyp/P9nY3Lk3NZIteJvu9sonsK89nXnYBzCE0pejW4=";
      };
    }
    {
      name = "typescript";
      path = fetchurl {
        name = "typescript@5.7.3";
        url  = "https://registry.npmjs.org/typescript/-/typescript-5.7.3.tgz";
        hash = "sha256-gM/KElS6uOgdY5F45C1kBthW+6bjTK1g0atQ7m5ffrs=";
      };
    }
    {
      name = "scheduler";
      path = fetchurl {
        name = "scheduler@0.25.0";
        url  = "https://registry.npmjs.org/scheduler/-/scheduler-0.25.0.tgz";
        hash = "sha256-iqwtpt7LCcHaz4wQb2LS+0RU+7H98vb+bU7xpXt8aRQ=";
      };
    }
    {
      name = "@types/node";
      path = fetchurl {
        name = "@types/node@22.13.5";
        url  = "https://registry.npmjs.org/@types/node/-/node-22.13.5.tgz";
        hash = "sha256-jtFd0kKkgHHRYLsT8YUk7PgWSyu0nVwrUHm+IMzNRKQ=";
      };
    }
    {
      name = "tailwindcss";
      path = fetchurl {
        name = "tailwindcss@4.0.9";
        url  = "https://registry.npmjs.org/tailwindcss/-/tailwindcss-4.0.9.tgz";
        hash = "sha256-kw0dfQQ5MRjcvU8Vrs5nTIsOWIsqqNx9tPFvk+xxSvQ=";
      };
    }
    {
      name = "bun-types";
      path = fetchurl {
        name = "bun-types@1.2.4";
        url  = "https://registry.npmjs.org/bun-types/-/bun-types-1.2.4.tgz";
        hash = "sha256-lXqzNu+EFE1bzON4rLGrSdws76vuyStC1Ehxa3n/6/0=";
      };
    }
    {
      name = "bun-plugin-tailwind";
      path = fetchurl {
        name = "bun-plugin-tailwind@0.0.14";
        url  = "https://registry.npmjs.org/bun-plugin-tailwind/-/bun-plugin-tailwind-0.0.14.tgz";
        hash = "sha256-nQViPxk9Oiz+kZWKoeA1k2MD/t+DMbIQLlOZUQk1TgA=";
      };
    }
    {
      name = "@types/react-dom";
      path = fetchurl {
        name = "@types/react-dom@19.0.4";
        url  = "https://registry.npmjs.org/@types/react-dom/-/react-dom-19.0.4.tgz";
        hash = "sha256-rJnqfJ6tOL2GEZ43gL3ib8C8wKNEqBZkKU3zm3kONDw=";
      };
    }
  ];

  # Extract a package from a tar file
  extractPackage = pkg:
    runCommand "bun2nix-extract-${pkg.name}" {buildInputs = [gnutar coreutils];} ''
      mkdir -p $out/${pkg.name}
      tar -xzf ${pkg.path} -C $out/${pkg.name} --strip-components=1
    '';

  # Build the node modules directory
  nodeModules = symlinkJoin {
    name = "node-modules";
    paths = map extractPackage packages;
  };
in {
  inherit nodeModules packages;
}