use serde::{Deserialize, Serialize};

#[derive(Default, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
/// # Prefetched Package
///
/// A model of the results returned by `nix-flake-prefetch <url>`
pub struct PrefetchedPackage {
    /// The prefetched hash of the package
    pub hash: String,
    /// The url to fetch the package from
    pub url: String,
    /// The name of the package in npm
    pub name: String,
}

/// # Nix Expression Conversion Trait
///
/// Implemented by anything that can be turned into a nix expression
pub trait DumpNixExpression {
    /// # Dump Nix Experession
    ///
    /// Dumps `self` into a nix expression
    fn dump_nix_expression(&self) -> String;
}

impl DumpNixExpression for PrefetchedPackage {
    fn dump_nix_expression(&self) -> String {
        format!(
"    {{
        name = \"{}\";
        path = fetchurl {{
            name = \"{}\";
            url  = \"{}\";
            hash = \"{}\";
        }};
    }}",
            self.name, self.name, self.url, self.hash
        )
    }
}

impl DumpNixExpression for Vec<PrefetchedPackage> {
    fn dump_nix_expression(&self) -> String {
        let packages_section = self
            .iter()
            .map(|p| p.dump_nix_expression())
            .reduce(|acc, e| acc + "\n" + &e)
            .unwrap_or_default();

        format!(
"# This file was autogenerated by `bun2nix`, editing it is not recommended.
# Consume it with `callPackage` in your actual derivation -> https://nixos-and-flakes.thiscute.world/nixpkgs/callpackage
{{ fetchurl, fetchgit, linkFarm, runCommand, gnutar }}: rec {{
  offline_cache = linkFarm \"offline\" packages;
  packages = [
{}
  ];
}}",
    packages_section)
    }
}

#[test]
fn test_dump_nix_expression_file_single() {
    let output = PrefetchedPackage {
        hash: "sha256-0294eb3dee05028d31ee1a5fa2c556a6aaf10a1b".to_owned(),
        url: "https://registry.npmjs.org/@alloc/quick-lru/-/quick-lru-5.2.0.tgz".to_owned(),
        name: "@alloc/quick-lru".to_owned()
    };

    let expected = 
"    {
        name = \"@alloc/quick-lru\";
        path = fetchurl {
            name = \"@alloc/quick-lru\";
            url  = \"https://registry.npmjs.org/@alloc/quick-lru/-/quick-lru-5.2.0.tgz\";
            hash = \"sha256-0294eb3dee05028d31ee1a5fa2c556a6aaf10a1b\";
        };
    }";

    assert_eq!(expected.trim(), output.dump_nix_expression().trim());
}

#[test]
fn test_dump_nix_expression_file_vec() {
    let out = vec![
        PrefetchedPackage {
            hash: "sha256-0294eb3dee05028d31ee1a5fa2c556a6aaf10a1b".to_owned(),
            url: "https://registry.npmjs.org/@alloc/quick-lru/-/quick-lru-5.2.0.tgz".to_owned(),
            name: "@alloc/quick-lru".to_owned()
        },
        PrefetchedPackage {
            hash: "sha256-149134391104193904109309431984918439183b".to_owned(),
            url: "https://registry.npmjs.org/@alloc/quick-lru/-/quick-lru-5.2.0.tgz".to_owned(),
            name: "@alloc/quick-lru".to_owned()
        }
    ];

    let expected = 
"# This file was autogenerated by `bun2nix`, editing it is not recommended.
# Consume it with `callPackage` in your actual derivation -> https://nixos-and-flakes.thiscute.world/nixpkgs/callpackage
{ fetchurl, fetchgit, linkFarm, runCommand, gnutar }: rec {
  offline_cache = linkFarm \"offline\" packages;
  packages = [
    {
        name = \"@alloc/quick-lru\";
        path = fetchurl {
            name = \"@alloc/quick-lru\";
            url  = \"https://registry.npmjs.org/@alloc/quick-lru/-/quick-lru-5.2.0.tgz\";
            hash = \"sha256-0294eb3dee05028d31ee1a5fa2c556a6aaf10a1b\";
        };
    }
    {
        name = \"@alloc/quick-lru\";
        path = fetchurl {
            name = \"@alloc/quick-lru\";
            url  = \"https://registry.npmjs.org/@alloc/quick-lru/-/quick-lru-5.2.0.tgz\";
            hash = \"sha256-149134391104193904109309431984918439183b\";
        };
    }
  ];
}";

    assert_eq!(expected.trim(), out.dump_nix_expression().trim());
}
